
utils::globalVariables(c("Data",
                         "data",
                         ".",

                         "MultiLab",
                         "ReplicationProject",
                         "Replication",
                         "C_N",
                         "T_N",
                         "T_M",
                         "SE_T_M",
                         "C_M",
                         "SE_C_M",
                         "T_SD",
                         "SE_T_SD",
                         "C_SD",
                         "SE_C_SD",
                         "MD",
                         "SE_MD",
                         "pooled_SD",
                         "SE_pooled_SD",
                         "SMD",
                         "SE_SMD",
                         "Rep_Stat",
                         "Model_Est",
                         "Tau",
                         "n",
                         "Statistic",
                         "dot_size",
                         "violin_plot",
                         "scatter_plot",
                         # functions
                         "ln_SD",
                         "SE_ln_SD",
                         # to be deleted
                         "MA__cor_pooled_SD_MD",
                         "MA__cor_pooled_SD_SMD",
                         "MA__cor_C_M_MD",
                         "MA__cor_T_M_MD",
                         "MA__cor_C_SD_T_SD"
))
